### ISSUE TITLE
i7z segf on Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz ( rev91 )

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Hypfer/i7z#55]
```
simply starting leads to direct segf.

(gdb) bt full
#0  0x00000000004027d3 in Print_Information_Processor 
(nehalem=nehalem@entry=0x60a3bc, sandy_bridge=sandy_bridge@entry=0x60a3bd) at 
helper_functions.c:348
        proc_info = {stepping = 106 'j', model = 126 '~', family = 64 '@', processor_type = 0 '\000', extended_model = 0 '\000', extended_family = 4226688}
        vendor_string = "GenuineIntel"
#1  0x00000000004018a2 in main (argc=1, argv=0x7fffffffce18) at i7z.c:354
        log_file_name = '\000' <repeats 999 times>
        log_file_name2 = '\000' <repeats 280 times>"\301, \026\253\252\252*", '\000' <repeats 67 times>, " \000\000\000\000\000\000T\036\000\000\000\000\000\000T\036", '\000' <repeats 14 times>, "\005\000\000\000\000\000\000\000\000  \000\000\000\000\000\000@ \000\000\000\000\000\200\060 \000\000\000\000\000\370\060 \000\000\000\000\000\000 \000\000\000\000\000\000\003", '\000' <repeats 167 times>, "\005\034\253\252\252*", '\000' <repeats 58 times>, "Ĩ\253\252\252*\000\000/\000\000\000\000\000\000\000\337xI\253\252*\000\000\000\000\000\000\000\000\000\000\332/\253\252\252*\000\000\022\000\000\000\000\000\000\000\000\220\071\000\000\000\000\000\000\360\071", '\000' <repeats 13 times>"\200, \303\377\377\377\177\000\000\375\325*\000\000X֬\252\001\000\000\000\220\271\356\252\000\000\000\000\200\303\377\377\377\177\000\000F\032\253\252\252*\000\000\000"...
        chi = {max_online_cpu = 32, num_sockets = 0, sibling_num = {1339847321, 0, 0, 0, 1339847321, 0, 0, 0, -1431590716, 10922, 837403428, 0, -1429393205, 
            10922, 0, 0, -1431621670, 10922, 0, 0, -1431205768, 10922, -1431513512, 10922, 0, 0, -1429417984, 10922, -1427188227, 10922, 0, 1, -1431621405, 
            0, 0, 0, -15352, 32767, 0, 0, -1431610183, 10922, -1429413520, 10922, 7, 10922, -15056, 1, 0, 0, -1431278091, 10922, 11, 0, 0, 0, 0, 0, 
            -1427196752, 10922, 4196703, 0, -1427195528, 10922, -12784, 32767, 832, 0, 1179403647, 65794, 0, 0, 4063235, 1, 3760, 0, 64, 0, 12696, 0, 0, 
            3670080, 4194314, 1769500, 6, 5, 64, 0, 64, 0, 64, 0, 560, 0, 560, 0, 8, 0, 3, 4, 6736, 0, 6736, 0, 6736, 0, 28, 0, 28, 0, 16, 0, 1, 5, 0, 0, 0, 
            0, 0, 0, 7764, 0, 7764, 0, 2097152, 0, 1, 6}, processor_num = {11608, 0, 2108760, 0, 2108760, 0, 808, 0, 928, 0, 2097152, 0, 2, 6, 11648, 0, 
            2108800, 0, 2108800, 0, 512, 0, 512, 0, 8, 0, 4, 4, 624, 0, 624, 0, 624, 0, 32, 0, 32, 0, 4, 0, -13296, 32767, -13200, 32767, 1, 0, -1427195504, 
            10922, -14560, 32767, -1421248289, 10922, -1431603166, 10922, 0, 0, -1431595562, 10922, -1429413840, 10922, -13304, 32767, -13312, 32767, -13313, 
            32767, -1431603216, 10922, -13296, 32767, 11608, 0, 0, 0, 2108760, 0, 0, 0, 680, 0, -1419141744, 10922, -1730150400, -1, 1, 0, -1427195504, 
            10922, -14560, 32767, -1421248289, 10922, -1948254208, -1, 728760320, 1431655767, 4, 16, 1, 5590599, 0, 2, 6, 9, 27, 27, 2, 7, 1114776, 67127424, 
            1073741842, -1643632509, 27, 0, 28, 0, 0, 29, 0, 30, 0, 31, 1, 0, -13200, 32767, 5, 0}, package_num = {-1431601038, 10922, 16843008, 65793, 
            -1431599002, 10922, -1427196728, 10922, -1429415528, 10922, 0, 0, 0, 0, -1431512288, 10922, -14112, 32767, -1429393205, 10922, -1431603166, 
            10922, 0, 0, -1431595562, 10922, -1429413840, 10922, -13304, 32767, -13312, 32767, -13313, 32767, -1431603216, 10922, -13296, 32767, 0, 0, 0, 0, 
            -1429413840, 10922, 0, 0, -13312, 32767, -1427219104, 10922, -1730150400, -1, 1, 0, -1431512288, 10922, -14112, 32767, -1429393205, 10922, 
            -1897922560, -1, 728760320, 1431655767, -1430892224, 10922, -1730150400, -1, 1, 0, -1431513512, 10922, -14112, 32767, -1431205768, 10922, 
            -1889533952, -1, 728760320, 1431655767, -1427218656, 10922, -13200, 32767, -1431602365, 10922, 1, 16916640, -1429415528, 10922, 0, 0, 218136768, 
            67112074, 1149763600, 1076758578, -1431616948, 10922, -1427219104, 10922, 0, 0, 1, 0, 2090760340, 0, -1429412056, 10922, -1431614726, 10922, 
            -13776, 32767, 32668130, 0, -1, 0, -1431518880, 10922, -1427196728, 10922, -1429415528, 10922, -13760, 32767, 0, 0, -1431518880, 10922}, 
          coreid_num = {-1431616948, 10922, -1431518712, 10922, 4, 0, 7, 0, 2090266759, 0, -1427193960, 10922, -1431614895, 10922, -13648, 32767, 32660418, 
            0, -1, 0, -1425048392, 10922, -1425048440, 10922, -13576, 32767, -13632, 32767, 127579, 0, -1425048392, 10922, -1429411192, 10922, -1424996120, 
            10922, -1431614125, 10922, 0, 0, -1419135008, 10922, -1427196728, 10922, -1431652652, 10922, -1424995832, 10922, -1431616948, 10922, 0, 1, 4, 0, 
            7, 0, -1322262249, 0, -1427193960, 10922, -1431614895, 10922, -13456, 32767, 46448516, 0, -1, 0, -1425048392, 10922, -1425056504, 10922, 
            -1419135008, 10922, -13440, 32767, 181439, 0, -1425048392, 10922, -1429415528, 10922, -1425044504, 10922, 0, 0, 0, 0, -1419136304, 10922, 
            -1427196728, 10922, -1429397850, 10922, -1424995832, 10922, -1429404736, 10922, 0, 1, 162, 1, -1427195528, 10922, -13256, 32767, -13296, 32767, 
            -1431616948, 10922, 1, 0, 0, 0, 1, 0, -7907219, 0, -1429412056, 10922, -1431614726, 10922, -13216, 32767, 66985313, 0, -1, 0}, display_cores = {
            -1431518880, 10922, 0, 0, -1431616948, 10922, -13200, 32767, 4, 0, 7, 0, -163754450, 0, -1427193960, 10922, -1431614895, 10922, -13120, 32767, 
            64550200, 0, -1, 0, -1425048392, 10922, -1425048892, 10922, -13008, 32767, -13104, 32767, 252149, 0, -1425048392, 10922, -13016, 32767, 
            -1424998832, 10922, -12960, 32767, 0, 0, -1419136928, 10922, -1427196728, 10922, 4196965, 0, -1424995832, 10922, 4195584, 0, 0, 1, 2065, 1, 0, 0, 
            -12920, 32767, -12960, 32767, -1419136928, 10922, 1, 0, -1429412664, 10922, -1429413520, 10922, -1431614125, 10922, 0, 0, -1419136928, 10922, 1, 
            0, 0, 0, 1, 10922, -1429413520, 10922, 115124853, 0, 10240, 0, -1431518688, 10922, -1429412096, 10922, -1427219552, 10922, -1429417984, 10922, 0, 
            0, -1429412664, 10922, -163754450, 0, -1423632128, 10922, 0, 0, 4196965, 0, -1, 0, 194, 0, -1424998832, 10922, -1427196728, 10922, 1, 0, 4198433, 
            0, 1, 0, 4224877, 0, 15774463, 0}, HT = false}
        socket_0 = {max_cpu = 0, socket_num = 0, processor_num = {-1, -1, -1, -1, -1, -1, -1, -1, 0 <repeats 24 times>}, num_physical_cores = 0, 
          num_logical_cores = 0}
        socket_1 = {max_cpu = 0, socket_num = 1, processor_num = {-1, -1, -1, -1, -1, -1, -1, -1, 0 <repeats 24 times>}, num_physical_cores = 0, 
          num_logical_cores = 0}
        c = <optimized out>
        presupplied_socket_info = false
        long_options = {{name = 0x407e64 "write", has_arg = 1, flag = 0x0, val = 119}, {name = 0x40795d "socket0", has_arg = 1, flag = 0x0, val = 122}, {
            name = 0x407965 "socket1", has_arg = 1, flag = 0x0, val = 121}, {name = 0x40796d "logfile", has_arg = 1, flag = 0x0, val = 108}, {
            name = 0x407975 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x40797a "nogui", has_arg = 0, flag = 0x0, val = 110}}



processor   : 7
vendor_id   : GenuineIntel
cpu family  : 6
model       : 42
model name  : Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
stepping    : 7
microcode   : 0x28
cpu MHz     : 1600.000
cache size  : 8192 KB
physical id : 0
siblings    : 8
core id     : 3
cpu cores   : 4
apicid      : 7
initial apicid  : 7
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat 
pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm 
constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc 
aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr 
pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm 
ida arat epb xsaveopt pln pts dts tpr_shadow vnmi flexpriority ept vpid
bogomips    : 6784.52
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

```

Original issue reported on code.google.com by `ju.lec...@googlemail.com` on 29 Jun 2012 at 4:41

**Comment by GoogleCodeExporter** [comment]
```
again an optimization issue. -O >1 makes it break
```

Original comment by `ju.lec...@googlemail.com` on 29 Jun 2012 at 4:55

**Comment by GoogleCodeExporter** [comment]
```
i started looking into this. first i thought it happened due to some flags but 
couldn't zero the issue.

doesn't seem to happen with gcc 4.6.3 but happens with 4.7.0. let me 
investigate more.
```

Original comment by `abhirana` on 30 Jun 2012 at 1:58
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
hi Justin

i fixed the issue in the latest commit.

it seems that get_vendor() in helper_functions.c borks strcmp() somehow, so i 
have to do strcmp() byte-by-byte; i'll look into the cpuid asm to see why that 
happens. seems to be working for (debian) gcc 4.6.3, 4.7.1 and with options 
-O(0-3). 

thanks
```

Original comment by `abhirana` on 4 Jul 2012 at 6:29
- Changed state: **Fixed**
